### ISSUE TITLE
The super constructor to "inherits" must not be null or undefined

### ISSUE THREAD

**Issue by simonbruneaud** [chris-l/mock-couch#51]
Weird error when I execute test with gulp or npm:

Here the sample of code from my test:

```
const mockCouch = require('mock-couch');
let couchdbMock;

describe('TEST', function() {
    before(function() {
        couchdbMock = mockCouch.createServer();
        couchdbMock.listen(5985);
    });

  // unit tests
```

I got this error comming from the line of code: `couchdbMock = mockCouch.createServer();`:

```
TypeError: The super constructor to "inherits" must not be null or undefined
      at Object.exports.inherits (util.js:989:11)
      at Object.<anonymous> (node_modules/spdy/lib/spdy/connection.js:86:6)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (node_modules/spdy/lib/spdy.js:20:19)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (node_modules/restify/lib/server.js:13:12)
      at require (internal/module.js:20:19)
      at Object.createServer (node_modules/restify/lib/index.js:95:18)
      at node_modules/mock-couch/index.js:122:25
      at Object.createServer (node_modules/mock-couch/index.js:158:6)
      at Context.<anonymous> (server/dao/dao.couchdb.spec.js:18:33)
```

The weird thing is I get this error when I execute the test with Gulp or npm, but I do not get any errors when I use mocha commands directly.

**Comment by joliejuke-orga** [comment]
hey @chris-l , Is this package still maintained?

**Comment by nullivex** [comment]
@joliejuke-orga @chris-l I am also having this same issue.

I am on the latest node and it seems to be the spdy package producing the issue. I am going to try forking and fixing. I will submit a PR if I get it.

Thanks

**Comment by nullivex** [comment]
I forked, updated the dependencies to latest and jshint failed 38 out of 39 files along with 96 test failures. It could just be my platform. I am going to leave this one for the maintainer.

For my package I am going to use real couch since I am already building on Travis-CI.

**Comment by chris-l** [comment]
Well, I have just uploaded a new commit that fixes that. There I'm using `npm shrinkwrap` to specify the working versions of the dependencies.

**Comment by nullivex** [comment]
Hi,
Okay great, I just tried the new package it seems to have given an error.

```
C:\Users\Mac\WebstormProjects\shredder-sdk>npm install mock-couch --save-dev
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-
fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Program Files (x86)\Nodist\v-x64\8.1.3\node.exe itself. Use the `
--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> dtrace-provider@0.6.0 install C:\Users\Mac\WebstormProjects\shredder-sdk\node_modules\mock-couch\node_modules\bunyan\node_modules\dtrace-provider
> node scripts/install.js

npm WARN shredder-sdk@1.2.0 No license field.

+ mock-couch@0.1.9
added 84 packages, removed 13 packages, updated 1 package and moved 27 packages in 17.263s

C:\Users\Mac\WebstormProjects\shredder-sdk>npm test
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Program Files (x86)\Nodist\v-x64\8.1.3\node.exe itself. Use the `
--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> shredder-sdk@1.2.0 test C:\Users\Mac\WebstormProjects\shredder-sdk
> node ./node_modules/mocha/bin/mocha ./test/*.test.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'restify'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mac\WebstormProjects\shredder-sdk\node_modules\mock-couch\index.js:4:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mac\WebstormProjects\shredder-sdk\mock\index.js:2:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Mac\WebstormProjects\shredder-sdk\test\mock.test.js:3:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at C:\Users\Mac\WebstormProjects\shredder-sdk\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\Mac\WebstormProjects\shredder-sdk\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (C:\Users\Mac\WebstormProjects\shredder-sdk\node_modules\mocha\lib\mocha.js:495:10)
    at Object.<anonymous> (C:\Users\Mac\WebstormProjects\shredder-sdk\node_modules\mocha\bin\_mocha:469:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! Test failed.  See above for more details.
```
It seems the mock-couch package is wanting me to install restify.

**Comment by nullivex** [comment]
I installed restify locally and got this.

```
     TypeError: restify.bodyParser is not a function
      at node_modules\mock-couch\index.js:144:23
      at Object.createServer (node_modules\mock-couch\index.js:158:6)
      at mock\index.js:28:31
      at tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:512:31)
      at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:569:18)
      at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:614:10)
      at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:693:18)
      at Promise._fulfill (node_modules\bluebird\js\release\promise.js:638:18)
      at Server.<anonymous> (node_modules\bluebird\js\release\nodeback.js:42:21)
      at emitListeningNT (net.js:1342:10)
      at _combinedTickCallback (internal/process/next_tick.js:99:11)
      at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

**Comment by chris-l** [comment]
For some reason, it seems restify wasn't installed when you did `npm install mock-couch --save-dev`.
And when you manually installed restify, it probably installed the lastest version, instead of the version specified by shrinkwrap.

The lastest version of restify don't have the `bodyParser` property directly attached to the exported obj, so that explains the second error.

**Comment by joliejuke-orga** [comment]
News about the restify issue?
