### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined

### ISSUE THREAD

**Issue by tejinderss** [chris-l/mock-couch#57]
> let mockCouch = mock.createServer();
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:1203:11)
    at Object.<anonymous> (C:\Users\TEJINDERSINGH\Projects\isc-common-configstore\configstorev1\node_modules\mock-couch\node_modules\spdy\lib\spdy\connection.js:86:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
>

**Comment by chris-l** [comment]
That was because restify wasn't being updated. I have changed the npm-shrinkwrap.json to reflect that, so try with the new version.
